#!/usr/bin/perl
use strict;
use warnings;

# Set global variables
my $VERSION = "1.0";
my $CURVERSION = "7.4";
my $NEWVERSION = "8.1";
my $CURPHPDIR = "/etc/apache2/mods-enabled";

# Begin app
print "updatephp version $VERSION\n";
print "==========================\n";

print "Update current OS apps? (Yn): ";
my $myinput = <>;
chop($myinput);
if (($myinput eq "y") || ($myinput eq "Y") || ($myinput eq ""))
{
	print "Running system updates...\n";
	system("apt update");
	system("apt upgrade");
	print "========\n";
	print "Complete\n";
	print "========\n";
}
print "Add official PHP repo? (Yn: ";
$myinput = <>;
chop($myinput);
if (($myinput eq "y") || ($myinput eq "Y") || ($myinput eq ""))
{
	system("add-apt-repository ppa:ondrej/php");
	system("apt update");
	system("apt upgrade");
}
print "Beginning to update mods...\n";
#system("a2dismod php$CURVERSION");
#system("a2enmod php$NEWVERSION");
print "Main php mod updated\n";

# Read in file list
opendir(DH, $CURPHPDIR);
my @files = readdir(DH);
closedir(DH);

# Loop for each file
foreach my $filename (@files)
{
	# skip . and ..
	next if ($filename =~ /^\.$/);
	next if ($filename =~ /^\.\.$/);
	my $type = substr($filename, -5);
	next if ($type ne ".conf");
	my $modname = substr($filename, 0, -5);
	next if ($modname eq "php$CURVERSION");
	print "Current mod is: $modname\n";
}
exit(0);
